### ISSUE TITLE
Show labels in docs view

### ISSUE THREAD

**Issue by Sephyr0s** [jimdrury/storybook-addon-badges#13]
Hi,

Thanks again for this awesome addon.

In Storybook v7 they splitted the docs/canvas view differently. This plugin only shows on the canvas views.

Since Storybook v7 we find ourselves using the Docs view in favor of the canvas view, but because of the limitation of the addon, we find ourselves missing the badges.

So the feature request is: is it possible to show the badges on the docs view in Storybook?

**Comment by geometricpanda** [comment]
Hey, i'll take a look into this later on - sorry for the delay, i didnt get an email

**Comment by Freytag** [comment]
I pulled down the latest code and noticed that this should be resolved with whats on main, looks like we're just waiting for a successful release to happen.

**Comment by jimdrury** [comment]
hey @Freytag, I've just checked myself, and you are right :) nice
