### ISSUE TITLE
Hovering mouse over badge doesn't show tooltip on Storybook v7

### ISSUE THREAD

**Issue by maximevaillancourt** [jimdrury/storybook-addon-badges#14]
Storybook version: v7.0.6

## Expected behavior

**Hovering badge with mouse show tooltips. ✅**

(optionally, clicking on the badge hides the visible tooltip)

Demo when using the add-on in Storybook v6:

https://user-images.githubusercontent.com/8457808/233484575-a015ace4-ebd5-43d6-8a90-4bafd83014dc.mov

## Actual behavior

**Hovering badge with mouse does not show tooltip. ❌**

(optionally, clicking on the badge toggles the tooltip visibility)  

Demo when using the add-on in Storybook v7:

https://user-images.githubusercontent.com/8457808/233484595-c6435515-cb32-43fa-9a41-0945de8c8a0e.mov

**Comment by jimdrury** [comment]
Hey,
This change was done by Storybook, you now have to click. I'll have a look at options though
