### ISSUE TITLE
Consider exporting types like BadgeConfig/BadgesConfig

### ISSUE THREAD

**Issue by DrJKL** [jimdrury/storybook-addon-badges#18]
If you're targeting TS 5+, you should be able to do `export type * from 'typings.interface.ts';` in the index. 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#support-for-export-type-

Otherwise, I think you'd have to enumerate them.

**Comment by jimdrury** [comment]
Looks like you sorted it for me. Great work!
