### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [jimdrury/storybook-addon-badges#20]
Hey @geometricpanda! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by JamesIves** [comment]
Just attempted a version 8 upgrade, and I'm seeing this error flagged by storybook-addon-badges:

```
❯ npx storybook@latest doctor
🩺 The doctor is checking the health of your Storybook..
╭ Incompatible packages found ───────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                    │
│   The following packages are incompatible with Storybook 8.0.0 as they depend on different major versions of Storybook packages:   │                                                   │
│   - @geometricpanda/storybook-addon-badges@2.0.2                                                                                   │                                                                              │                                                                                             │
│                                                                                                                                    │
│                                                                                                                                    │
│   Please consider updating your packages or contacting the maintainers for compatibility details.                                  │
│   For more on Storybook 8 compatibility, see the linked GitHub issue:                                                              │
│   https://github.com/storybookjs/storybook/issues/26031                                                                            │
│                                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by carlwelchyubico** [comment]
I'm able to successfully display Badges, But I see this error when starting up 8.04
```
15% building 0/2 entries 62/161 dependencies 4/42 modulesWARN Failed to parse .storybook/preview.ts with react-docgen. Please use the below error message and the content of the file which causes the error to report the issue to the maintainers of react-docgen. https://github.com/reactjs/react-docgen
SyntaxError: ./.storybook/preview.ts: Unexpected token, expected "}" (37:18)

  35 |     },
  36 |     badgesConfig: <BadgesConfig>{
> 37 |       [BADGE.BETA]: {
     |                   ^
  38 |         styles: {
  39 |           backgroundColor: '#FFF',
  40 |           borderColor: '#018786',
  ```

**Comment by math-bourgeois** [comment]
Do we know when a new release will be created to include this fix?

**Comment by Freytag** [comment]
I pulled down the latest code and noticed that this should be resolved with whats on main, looks like we're just waiting for a successful release to happen.

**Comment by fpcoutinho** [comment]
Any news on the release of the new version? 😔 
It looks like it broke on the yarn publishing process.

**Comment by andrew-y0u** [comment]
@geometricpanda, could you release the new version by any chance?

**Comment by jimdrury** [comment]
Yeah I'll give it a try when I get to my laptop. I fear it's gonna end in debugging however

**Comment by sense-design** [comment]
We would love to have the 8.x compatibility for a current project we have set up.

**Comment by andrew-y0u** [comment]
🆙

**Comment by drjonnicholson** [comment]
Also looking forward to v8 compatibility :) @geometricpanda any progress?

**Comment by alico-cra** [comment]
Happy to test out if needed, excited for the release!

**Comment by Freytag** [comment]
I'm pretty sure it was just a [release](https://github.com/geometricpanda/storybook-addon-badges/actions/runs/8745338894/job/24000144951#step:7:107) issues that happened. As i mentioned in this issue https://github.com/geometricpanda/storybook-addon-badges/issues/25

**Comment by heddal** [comment]
Would also appreciate v8 compatibility 🤩

**Comment by carlwelchyubico** [comment]
![image](https://github.com/user-attachments/assets/c6d9af89-1656-4392-ac85-564535f4891e)

**Comment by masoudmanson** [comment]
Just upgraded to the latest Storybook and getting this warning!

```js
WARN The following packages are incompatible with Storybook 8.2.9 as they depend on different major versions of Storybook packages:
WARN - @geometricpanda/storybook-addon-badges@2.0.2
```

@geometricpanda, Any updates on this?? 😅😬

**Comment by jimdrury** [comment]
So I'm waiting for Storybook to come back to with proposed changes as they have suggestions for how this should work.

**Comment by alico-cra** [comment]
Super helpful for context, thanks for replying and feel free to keep us updated.

**Comment by jimdrury** [comment]
So i've fixed the dodgy release pipeline, hopefully that will have solved the compatibility thanks to the work @evg4b did.

I'm going to close this for now, please feel free to comment if you're experiencing issues
