### ISSUE TITLE
Add tags support

### ISSUE THREAD

**Issue by shilman** [jimdrury/storybook-addon-badges#21]
Hi @geometricpanda raising this comment as its own issue as a possibly annoying attempt to get your attention. I believe that updating your package to work with tags would close all three open issues on your repo.

_Originally posted by @shilman in https://github.com/geometricpanda/storybook-addon-badges/issues/17#issuecomment-2000907989_

I'm currently writing up the release post for the 8.1 tags feature and would like to highlight the updated badges addon if we can figure out out in the next month so. If not, we can always come back to it again later. Sorry for the noise and thanks for all your hard work on this high quality addon!

**Comment by jimdrury** [comment]
Hey there, if you can reach out to me on Twitter I'm certainly up for having a chat @Jim_Drury

**Comment by shilman** [comment]
@geometricpanda Thanks! It says I need to upgrade to message you unless you follow me `@mshilman`

Alternatively we can chat on Discord if you're there https://discord.gg/storybook

**Comment by Sidnioulz** [comment]
Hey folks, I was wondering what the status was on this ticket?

**Comment by Sidnioulz** [comment]
With some quick hacking, I could get the badge toolbar to read tags instead of badges. What would need to change is how you filter which tags to display as badges, and possibly how you provide `badgesConfig`.

In particular, `badgesConfig` would continue to be available in a preview context, but not in a manager context for e.g. displaying badges in the sidebar. So if you still wanted sidebar badges, you'd need to decide whether to remove per-story configs or whether to limit configs to e.g. tooltips and to display degraded badges with no tooltips in the sidebar.

**Comment by Sidnioulz** [comment]
@geometricpanda just pinging you here as there are still constraints with what can be done in the sidebar, even if you switch to using tags as a source of data. We still wouldn't be able to customise badges with story params, we'd need to do it with addon config for the whole SB instance instead.

**Comment by jimdrury** [comment]
So I've got it working, I'm just trying to publish it right now - out of date actions

It's got issues, but works when you view a specific story

**Comment by Sidnioulz** [comment]
GitHub actions requires so much more maintenance than CircleCI or GitLab :/ I feel your pain.

Happy to have a chat if you want to discuss how data flows in Storybook or to re-explore options for mapping badges to stories without loading the stories.

**Comment by jimdrury** [comment]
Yeah I'd love to have that chat - if you reach out to me on Twitter we can chat directly via dm if you like (@Jim_Drury)

**Comment by Sidnioulz** [comment]
I'm not on Twitter sadly! We've started a new addon to make the switch without bothering you with extra work, as @shilman told me you were busy these days. Is it ok if I email you so we can set a date and show you where we've been?
