### ISSUE TITLE
Leaf nodes in the sidebar get their title rendered, instead of their name

### ISSUE THREAD

**Issue by DanielRose** [jimdrury/storybook-addon-badges#26]
In Storybook stories CSF, the `Meta` information can contain an explicit `title` or a `component`, from which a title can be generated. Similarly, the individual stories can contain an explicit `name`, otherwise the name is calculated from the named export.

The title is used to generate a tree in the sidebar. The name is used as the name of the leaf node.

However, when using 2.0.4 of this package, the leaf node instead gets rendered with the title. For example, "Components/Grids" (which is the same for all leaf nodes) is shown for each story (and the docs page) in the Components => Grids tree.

**Comment by jimdrury** [comment]
Thank you so much for catching this. Happy to share that your PR merged and released. This problem should be solved.
