### ISSUE TITLE
Cannot import BADGE from package

### ISSUE THREAD

**Issue by MasterOdin** [jimdrury/storybook-addon-badges#4]
Looking to upgrade to 1.0.1 and I'm hitting the following TS error:

```
file.tsx:1:10 - error TS2614: Module '"@geometricpanda/storybook-addon-badges"' has no exported member 'BADGE'. Did you mean to use 'import BADGE from "@geometricpanda/storybook-addon-badges"' instead?

1 import { BADGE } from '@geometricpanda/storybook-addon-badges';
```

When I inspect the export, it's just `default: {}`, so if I were to do:

```ts
import foo from '@geometricpanda/storybook-addon-badges';
```

then `foo` is going to be `{}` which doesn't seem useful.

I think that [`src/index.ts`](https://github.com/geometricpanda/storybook-addon-badges/blob/main/src/index.ts) should be re-exporting [`src/shared.ts`](https://github.com/geometricpanda/storybook-addon-badges/blob/main/src/shared.ts)?

**Comment by jimdrury** [comment]
Yeah you're absolutely right, i'm working on it as we speak

**Comment by jimdrury** [comment]
This should be resolved now, please re-open if you're still experiencing issues
