### ISSUE TITLE
How to add tooltip in MDX?

### ISSUE THREAD

**Issue by tomasvn** [jimdrury/storybook-addon-badges#5]
How do you pass in tooltip config? In the example is only using badges. Also facing same problem after upgrading to 1.0.1, downgrading back to 0.2.2 #4 

```MDX
import { Meta } from '@storybook/addon-docs/blocks';
import { BADGE } from '@geometricpanda/storybook-addon-badges';

<Meta title="Path/To/MyComponent" parameters={{ badges: [BADGE.BETA] }} />;
```

**Comment by jimdrury** [comment]
So as far as the tooltip config goes, you set that in your `preview.js` when configuring the badge
i'm just resolving the issue with the import path right now

**Comment by jimdrury** [comment]
This should be resolved now, please re-open if you're still experiencing issues
